### ISSUE TITLE
CONTATO DE PARCERIA

### ISSUE THREAD

**Issue by edujr1** [Lord-of-the-Bots/BTC-price-overlay#1]
Fala Lord! Vi sua mensagem no bot e vim aqui ver.... tambem sou dev... Tenho um baita projeto promissor em TS nessa area de cripto e queria saber se voce gostaria de contribuir para ver se conseguimos alcançar um objetivo juntos?! tenho uma comunidade no TG onde varias pessoas estão nessa corrida juntos, mas ate agora nada.
Acredito que voce tenha um certo potencial pela qualidade do teu projeto do NSW Library... Se interessar me chama no TG. @Edujr1

**Comment by Lord-of-the-Bots** [comment]
Obrigado pela oferta - no momento não tenho interesse em participar de outros projetos devido à minha elevada carga de trabalho.

**Comment by edujr1** [comment]
> Obrigado pela oferta - no momento não tenho interesse em participar de outros projetos devido à minha elevada carga de trabalho.

Ta otimo! Qualquer mudança de opiniao ou necessidade de colaboraçao ai do seu lado, pode contar comigo!
